# Generated by Django 6.0 on 2025-12-09 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kothachahiyo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="location",
        ),
        migrations.AddField(
            model_name="room",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kothachahiyo.city",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kothachahiyo.district",
            ),
        ),
    ]
