"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-&h1+&c8!a1a0w=4e*80trn8@^xy8ar7r+1_u8f1#%b33do1nm9"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "kotha_chahiyo",
    "todo",
    'account',
    # SimpleJWT for JWT authentication
    'rest_framework_simplejwt',
    # Token blacklist app - allows us to blacklist tokens on logout
    # This is required for secure logout functionality
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'hs_python_db',
#         'USER': 'django_user',
#         'PASSWORD': 'Password123!',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# }


# Django REST Framework Configuration
# This configures how our API handles authentication and permissions
REST_FRAMEWORK = {
    # Default authentication method - JWT (JSON Web Token)
    # JWT tokens are more secure and scalable than regular tokens
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Default permission - users must be authenticated to access API
    # This can be overridden in individual views if needed
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# SimpleJWT Configuration
# These settings control how JWT tokens work in our application
from datetime import timedelta

SIMPLE_JWT = {
    # Access Token: Short-lived token (15 minutes) used for API requests
    # This is the token you send with each request to authenticate
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    
    # Refresh Token: Long-lived token (7 days) used to get new access tokens
    # When access token expires, use refresh token to get a new one
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    
    # Rotate Refresh Tokens: If True, a new refresh token is issued each time you refresh
    # This is more secure - old refresh tokens become invalid
    'ROTATE_REFRESH_TOKENS': True,
    
    # Blacklist After Rotation: If True, old refresh tokens are blacklisted
    # This prevents reuse of old tokens if they were stolen
    'BLACKLIST_AFTER_ROTATION': True,
    
    # Algorithm used to sign tokens (HS256 is symmetric, RS256 is asymmetric)
    # HS256 is simpler and works well for most applications
    'ALGORITHM': 'HS256',
    
    # Secret key for signing tokens (uses Django's SECRET_KEY by default)
    'SIGNING_KEY': SECRET_KEY,
    
    # Token type in the response header (usually "Bearer")
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    
    # Token type claim in the token payload
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    # User ID claim in the token payload
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
