"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment Configuration
# Set ENVIRONMENT=local for development, ENVIRONMENT=production for live server
ENVIRONMENT = config("ENVIRONMENT", default="local")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Get from environment variable, fallback to default (ONLY for local development!)
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-&h1+&c8!a1a0w=4e*80trn8@^xy8ar7r+1_u8f1#%b33do1nm9",
)

# SECURITY WARNING: don't run with debug turned on in production!
# In production, DEBUG must be False!
DEBUG = config("DEBUG", default=True, cast=bool)

# Allowed Hosts - comma-separated list in production
# Example: ALLOWED_HOSTS=yourdomain.com,www.yourdomain.com
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="*", cast=Csv())


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "account",
    "todo",
    # SimpleJWT for JWT authentication
    "rest_framework_simplejwt",
    # Token blacklist app - allows us to blacklist tokens on logout
    # This is required for secure logout functionality
    "rest_framework_simplejwt.token_blacklist",
    "kothachahiyo",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database configuration based on environment
DATABASE_ENGINE = config("DATABASE_ENGINE", default="sqlite3")

if DATABASE_ENGINE == "postgresql":
    # PostgreSQL (Recommended for Production)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DATABASE_NAME", default=""),
            "USER": config("DATABASE_USER", default=""),
            "PASSWORD": config("DATABASE_PASSWORD", default=""),
            "HOST": config("DATABASE_HOST", default="localhost"),
            "PORT": config("DATABASE_PORT", default="5432"),
        }
    }
elif DATABASE_ENGINE == "mysql":
    # MySQL (Alternative for Production)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": config("DATABASE_NAME", default=""),
            "USER": config("DATABASE_USER", default=""),
            "PASSWORD": config("DATABASE_PASSWORD", default=""),
            "HOST": config("DATABASE_HOST", default="localhost"),
            "PORT": config("DATABASE_PORT", default="3306"),
        }
    }
else:
    # SQLite (Default for Local Development)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Django REST Framework Configuration
# This configures how our API handles authentication and permissions
REST_FRAMEWORK = {
    # Default authentication method - JWT (JSON Web Token)
    # JWT tokens are more secure and scalable than regular tokens
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # Default permission - users must be authenticated to access API
    # This can be overridden in individual views if needed
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
}

# SimpleJWT Configuration
# These settings control how JWT tokens work in our application
from datetime import timedelta

SIMPLE_JWT = {
    # Access Token: Short-lived token (15 minutes) used for API requests
    # This is the token you send with each request to authenticate
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    # Refresh Token: Long-lived token (7 days) used to get new access tokens
    # When access token expires, use refresh token to get a new one
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    # Rotate Refresh Tokens: If True, a new refresh token is issued each time you refresh
    # This is more secure - old refresh tokens become invalid
    "ROTATE_REFRESH_TOKENS": True,
    # Blacklist After Rotation: If True, old refresh tokens are blacklisted
    # This prevents reuse of old tokens if they were stolen
    "BLACKLIST_AFTER_ROTATION": True,
    # Algorithm used to sign tokens (HS256 is symmetric, RS256 is asymmetric)
    # HS256 is simpler and works well for most applications
    "ALGORITHM": "HS256",
    # Secret key for signing tokens (uses Django's SECRET_KEY by default)
    "SIGNING_KEY": SECRET_KEY,
    # Token type in the response header (usually "Bearer")
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    # Token type claim in the token payload
    "TOKEN_TYPE_CLAIM": "token_type",
    # User ID claim in the token payload
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # For production: collectstatic command

# Media files (User uploaded files - Images, etc.)
# https://docs.djangoproject.com/en/6.0/topics/files/

# Storage Type: 'local' or 'cloud'
STORAGE_TYPE = config("STORAGE_TYPE", default="local")

if STORAGE_TYPE == "cloud":
    # Cloud Storage Configuration (Production)
    # Option 1: AWS S3 (Most Popular)
    # Uncomment and configure if using AWS S3:
    # INSTALLED_APPS.append("storages")
    # DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    # STATICFILES_STORAGE = "storages.backends.s3boto3.S3StaticStorage"
    # AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID", default="")
    # AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY", default="")
    # AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME", default="")
    # AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME", default="us-east-1")
    # AWS_S3_CUSTOM_DOMAIN = config("AWS_S3_CUSTOM_DOMAIN", default="")
    # AWS_S3_FILE_OVERWRITE = False
    # AWS_DEFAULT_ACL = "public-read"
    # MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"

    # Option 2: Cloudinary (Easier for Beginners)
    # Uncomment and configure if using Cloudinary:
    # INSTALLED_APPS.append("cloudinary")
    # INSTALLED_APPS.append("cloudinary_storage")
    # DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
    # import cloudinary
    # cloudinary.config(
    #     cloud_name=config("CLOUDINARY_CLOUD_NAME", default=""),
    #     api_key=config("CLOUDINARY_API_KEY", default=""),
    #     api_secret=config("CLOUDINARY_API_SECRET", default=""),
    # )

    # For now, fallback to local if cloud storage not configured
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"
else:
    # Local Storage (Development)
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"

# Security Settings for Production
if ENVIRONMENT == "production":
    # Security settings that should be enabled in production
    SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=False, cast=bool)
    SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=True, cast=bool)
    CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=True, cast=bool)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
