"""
Todo Models - Database structure for Todo items
Models define the database tables and their fields
"""

from django.db import models
from django.contrib.auth.models import User


class Todo(models.Model):
    """
    Todo Model - Represents a single todo item in the database

    Fields:
    - user: Foreign key to User model (who owns this todo)
    - title: Short title/name of the todo (max 50 characters)
    - description: Detailed description of what needs to be done
    - created_at: Timestamp when the todo was created (auto-set)
    - id: Primary key (auto-generated by Django)
    """

    # ForeignKey creates a relationship to the User model
    # on_delete=models.CASCADE means if user is deleted, all their todos are deleted too
    # related_name='todo' allows us to access todos from a user: user.todo.all()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="todo")

    # CharField stores text with a maximum length
    # max_length=50 means title can be at most 50 characters
    title = models.CharField(max_length=50)

    # TextField stores longer text without length limit
    # Used for descriptions that might be long
    description = models.TextField()

    # DateTimeField stores date and time
    # auto_now_add=True means this is automatically set when todo is created
    # You don't need to provide this value - Django sets it automatically
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """
        String representation of the Todo object
        This is what you'll see in Django admin and when printing the object
        Returns the title of the todo
        """
        return self.title

    class Meta:
        # Order todos by creation date (newest first)
        # This affects how todos are displayed in queries
        ordering = ["-created_at"]
