# Generated by Django 6.0 on 2026-01-13 18:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='CultureAndTradition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='culture_tradition_image/')),
                ('about', models.TextField()),
                ('history', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_image/')),
                ('about', models.TextField(null=True)),
                ('history', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tourism',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='tourism_image')),
                ('about', models.TextField()),
                ('history', models.TextField(blank=True, null=True)),
                ('location', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourism', to='culture_tourism.cities')),
            ],
        ),
        migrations.CreateModel(
            name='TripPlanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banner')),
                ('contact_person_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=15)),
                ('tourism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_planner', to='culture_tourism.tourism')),
            ],
        ),
    ]
