# Generated by Django 6.0 on 2026-01-23 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripplanner',
            name='tourism',
        ),
    ]
