# Generated by Django 6.0 on 2026-01-23 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripplanner',
            name='tourism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_planner', to='culture_tourism.tourism'),
        ),
    ]
